apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: discount-model
  namespace: dev
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
spec:
  predictor:
    sklearn:
      storageUri: s3://models/discount-decisioning/v1
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
