apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: dev
  annotations:
    serving.kserve.io/s3-endpoint: seaweedfs-s3.seaweedfs-system.svc:8333
    serving.kserve.io/s3-usehttps: "0"
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: any
  AWS_SECRET_ACCESS_KEY: any
